name: master_detail
description: Responsive Master/Detail
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  
flutter:
  uses-material-design: true
